version: '3.7'

services:
  agent: &agent
    env_file:
      - .env
    volumes:
      - ./buildkite:/buildkite/
      - /buildkite/bin:/buildkite/bin
      - /buildkite/builds:/buildkite/builds

  agent-maven:
    <<: *agent
