#!/bin/bash

case "$1" in
  store|erase)
    exit 0
    ;;
esac

# some build steps use the assume role plugin, which overrides default environment
# variables with that role. unset those so we are forced to use the metadata
# endpoints
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_SESSION_TOKEN

docker-credential-ecr-login "$@"
