#!/bin/bash

case "$1" in
  store|erase)
    exit 0
    ;;
esac

# some build steps use the assume role plugin, which sets these environment
# variables with the credentials from assume role. also, the helper overrides
# any explicit docker login in the config file.
#
# unset those so we are forced to use the metadata endpoints and use the
# ec2 or ecs credentials
#
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_SESSION_TOKEN

docker-credential-ecr-login "$@"
