#!/bin/bash

case $1 in
	get)
		echo '{"ServerURL":"registry.dev.true.sh","Username":"buildkite-docker","Secret":"7de3ZZoT5JMMOzrM5Ayu"}'
		;;
	store)
		# what to do?
		exit
		;;
	erase)
		echo 'not implemented' >&2
		exit 1
		;;
	list)
		echo '{"https://registry.dev.true.sh":"buildkite-docker"}'
		;;
	version)
		echo 0.0.1
		;;
	*)
		exit 1
esac
