version: '3.2'
volumes:
  buildkite-builds: {}
  buildkite-plugins: {}
services:
  agent:
    build: .
    environment:
      - BUILDKITE_AGENT_TAGS=environment=local,queue=agent-dev
      - AWS_REGION=us-west-2
      - AWS_ACCOUNT_ID=221344006312
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - buildkite-plugins:/buildkite/plugins
      - buildkite-builds:/buildkite/builds
      - ./test/:/test
