version: '3.2'
services:
  agent:
    build: .
    environment:
      - BUILDKITE_AGENT_TOKEN
      - BUILDKITE_AGENT_TAGS=environment=local,queue=agent-dev
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
