version: '3.2'
services:
  agent:
    build: .
    environment:
      - BUILDKITE_AGENT_TAGS=environment=local,queue=agent-dev
    env_file:
      - .env
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./test/:/test
      - ./entrypoint.sh:/buildkite-entrypoint.sh
