#!/bin/bash

set -euo pipefail

name="$1"

exec aws lambda invoke \
     --function-name build-numbers \
     --invocation-type RequestResponse \
     --payload "\"${name}\"" \
     /dev/fd/3 3>&1 1>/dev/null
