steps:
  - label: ':docker: Build'
    plugins:
      - docker-compose#v3.0.3:
          build: agent
          image-repository: $REGISTRY_HOST/cache/buildkite

  - wait

  - label: Test
    plugins:
      - docker-compose#v3.0.3:
          run: agent
          command: [ --version ]

  - wait

  - label: ':docker: Push final image'
    plugins:
      - docker-compose#v3.0.3:
          push:
            - agent:$REGISTRY_HOST/buildkite:${BUILDKITE_BUILD_NUMBER}
