steps:
  - label: ':docker: Build'
    plugins:
      - docker-compose#v3.0.3:
          build: agent
          image-repository: $REGISTRY_HOST/cache/buildkite
          cache-from: agent:$REGISTRY_HOST/cache/buildkite:latest

  - wait

  - label: ':docker: Push cache:latest image'
    plugins:
      - docker-compose#v3.0.3:
          push:
            - agent:$REGISTRY_HOST/cache/buildkite:latest


  - label: Test
    commands:
      - '[[ -x /buildkite/bootstrap-via-docker ]]'
      # ensure /buildkite volume has captured the binary linked into the /buildkite/bin dir before volume's creation
      - /buildkite/bin/buildkite-agent --version
      # ensure the rest of these tools are at least runnable
      - jq --version
      - docker-compose version
      - docker version
      - aws --version
      - docker-credential-ecr-login version
    plugins:
      - docker-compose#v3.0.3:
          run: agent

  - wait

  - label: ':docker: Push final image'
    plugins:
      - docker-compose#v3.0.3:
          push:
            - agent:$REGISTRY_HOST/buildkite:${BUILDKITE_BUILD_NUMBER}
            - agent:$REGISTRY_HOST/buildkite:latest
