steps:
  - label: ':docker: Build'
    plugins:
      - docker-compose#v3.0.3:
          build: agent
          image-repository: $REGISTRY_HOST/cache/buildkite
          cache-from: agent:$REGISTRY_HOST/cache/buildkite:latest

  - wait

  - label: ':docker: Push cache:latest image'
    plugins:
      - docker-compose#v3.0.3:
          push:
            - agent:$REGISTRY_HOST/cache/buildkite:latest


  - label: Test
    command: bash /test.sh
    plugins:
      - docker-compose#v3.0.3:
          run: agent
          volumes:
            - ./test.sh:/test.sh

  - wait

  - label: ':docker: Push final image'
    plugins:
      - docker-compose#v3.0.3:
          push:
            - agent:$REGISTRY_HOST/buildkite:${BUILDKITE_BUILD_NUMBER}
            - agent:$REGISTRY_HOST/buildkite:latest
