steps:
  - label: ':docker: Build'
    plugins:
      - docker-compose#v3.0.3:
          build: agent
          image-repository: $REGISTRY_HOST/cache/buildkite
          cache-from: agent:$REGISTRY_HOST/cache/buildkite:latest

  - wait

  - label: ':docker: Push cache:latest image'
    plugins:
      - docker-compose#v3.0.3:
          push:
            - agent:$REGISTRY_HOST/cache/buildkite:latest


  - label: Test
    command: bash /test.sh
    plugins:
      - docker-compose#v3.0.3:
          run: agent

  - wait

  - label: ':docker: Push final image :latest'
    plugins:
      - docker-compose#v3.0.3:
          push:
            - agent:$REGISTRY_HOST/buildkite:latest

  - label: ':docker: Push final image :${BUILDKITE_BUILD_NUMBER}'
    plugins:
      - docker-compose#v3.0.3:
          push:
            - agent:$REGISTRY_HOST/buildkite:${BUILDKITE_BUILD_NUMBER}

  - wait
  - command: buildkite-agent meta-data set docker.image_repo $REGISTRY_HOST/buildkite:${BUILDKITE_BUILD_NUMBER}
