steps:
  - label: ':docker: Build'
    plugins:
      - docker-compose#v3.0.3:
          build: agent
          image-repository: $REGISTRY_HOST/cache/buildkite
          cache-from: agent:$REGISTRY_HOST/cache/buildkite:latest

  - wait

  - label: ':docker: Push cache:latest image'
    plugins:
      - docker-compose#v3.0.3:
          push:
            - agent:$REGISTRY_HOST/cache/buildkite:latest


  - label: Test
    command: bash /test/test.sh
    plugins:
      - docker-compose#v3.0.3:
          run: agent
          volumes:
            - maven-repo:/mnt/maven
          env:
            - ARTIFACTORY_API_KEY
            - ARTIFACTORY_API_USER
    env:
      ARTIFACTORY_API_KEY: foo
      ARTIFACTORY_API_USER: buildkite

  - label: ':docker: Push test image :test'
    plugins:
      - docker-compose#v3.0.3:
          push:
            - agent:$REGISTRY_HOST/buildkite:test
  
  - wait

  - label: Update test service
    command: aws ecs update-service --force-new-deployment --cluster sp-build-buildkite-cluster --service ylim-test-bk --region us-west-2
    agents:
      queue: 'deploy'

  - wait
  
  - label: Integration tests
    command: /test/integration-tests.sh
    env:
      ARTIFACTORY_USER: ssm-parameter:/build/common/artifactory-user
      ARTIFACTORY_PASS: ssm-parameter:/build/common/artifactory-password
    agents:
      queue: 'test'


#  - label: ':docker: Push final image :latest'
#    plugins:
#      - docker-compose#v3.0.3:
#          push:
#            - agent:$REGISTRY_HOST/buildkite:latest
#  - wait

#  - label: ':docker: Push final image :${BUILDKITE_BUILD_NUMBER}'
#    plugins:
#      - docker-compose#v3.0.3:
#          push:
#            - agent:$REGISTRY_HOST/buildkite:${BUILDKITE_BUILD_NUMBER}

#  - wait

#  - command: buildkite-agent meta-data set docker.image_repo $REGISTRY_HOST/buildkite:${BUILDKITE_BUILD_NUMBER}
